language: python

python:
- 3.7
dist: bionic
sudo: true

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - pip install pylint
  - pip install -r requirements.txt

script:
  - pylint --version
  - pylint app.py

notifications:
  on_success: change
  on_failure: change
